# Generated by Django 3.0 on 2019-12-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleType', models.CharField(max_length=128)),
                ('pers', models.IntegerField()),
            ],
        ),
    ]
