# Generated by Django 3.0 on 2019-12-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Sale'),
        ),
    ]
